"""
Karen's Ear — Raw Emergency Report Schemas
Strictly adheres to docs/data-schema.md Section 2.1 and docs/api-contract.md Section 3.
"""
from typing import Any, Optional
import uuid
from pydantic import Field, model_validator

from backend.app.schemas.common import (
    IsoUtcDatetime,
    KarenBaseModel,
    LocationPrecision,
    SourceType,
)


class LocationHint(KarenBaseModel):
    """
    Location hint provided with a report.
    Coordinates must remain null unless verified.
    """
    raw_text: Optional[str] = Field(default=None, description="Raw location phrasing")
    latitude: Optional[float] = Field(
        default=None,
        ge=-90.0,
        le=90.0,
        description="Verified latitude or null",
    )
    longitude: Optional[float] = Field(
        default=None,
        ge=-180.0,
        le=180.0,
        description="Verified longitude or null",
    )
    precision: LocationPrecision = Field(
        default=LocationPrecision.UNKNOWN,
        description="Geographic coordinate precision",
    )


class RawReportCreate(KarenBaseModel):
    """
    Ingestion payload for POST /reports.
    Enforces text length [3, 4000] and mandatory synthetic flag.
    """
    report_id: Optional[str] = Field(
        default=None,
        description="Optional client-generated ID; generated by backend if omitted",
    )
    text: str = Field(
        ...,
        min_length=3,
        max_length=4000,
        description="Emergency dispatch text content",
    )
    source: SourceType = Field(..., description="Origin source category")
    is_synthetic: bool = Field(..., description="True if simulator run, false for real dispatches")
    reported_at: IsoUtcDatetime = Field(..., description="ISO-8601 UTC timestamp of report event")
    location_hint: Optional[LocationHint] = Field(
        default=None,
        description="Optional location hint",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Arbitrary caller or channel metadata",
    )

    @model_validator(mode="after")
    def ensure_report_id(self) -> "RawReportCreate":
        if not self.report_id or not self.report_id.strip():
            self.report_id = f"rep-{uuid.uuid4()}"
        else:
            self.report_id = self.report_id.strip()
        return self

    @model_validator(mode="after")
    def validate_synthetic_guardrail(self) -> "RawReportCreate":
        src = self.source.value if hasattr(self.source, "value") else str(self.source)
        if src == "simulator" and not self.is_synthetic:
            raise ValueError("Reports with source 'simulator' must have is_synthetic set to True.")
        if src == "manual" and self.is_synthetic:
            raise ValueError("Reports with source 'manual' must have is_synthetic set to False.")
        return self


class RawReportResponse(KarenBaseModel):
    """
    Canonical representation of an ingested raw report.
    """
    report_id: str
    text: str
    source: str
    is_synthetic: bool
    reported_at: IsoUtcDatetime
    location_hint: Optional[LocationHint] = None
    metadata: Optional[dict[str, Any]] = Field(default=None, validation_alias="metadata_")
    ingested_at: IsoUtcDatetime
